package desktopclient;

import MailService.MailService;
import firealaramserver.FireRemoteInterface;
import java.rmi.Naming;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.List;
import java.util.ArrayList;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author mac
 */
public class ClientHome extends javax.swing.JFrame {

    /**
     * Creates new form ClientHome
     */
    
     
    
    public ClientHome() {
       
        initComponents();
        
         Timer timer = new Timer();
            int begin = 0;
            int timeInterval = 3000;
            timer.schedule(new TimerTask() {
                int counter = 0;
                     @Override
                    public void run() {
                         //call the method
                          display();
                            showTable();
                            
                            
                    counter++;
                    
                }
            }, begin, timeInterval);
            
            
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        add_senser_btn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sensor_ID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        floor_number = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        room_number = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Display = new javax.swing.JTable();
        message_view_btn = new javax.swing.JButton();
        edit_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        add_senser_btn.setText("Add Sensor");
        add_senser_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_senser_btnActionPerformed(evt);
            }
        });

        jLabel1.setText("Senser ID :");

        jLabel2.setText("Floor Number :");

        floor_number.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                floor_numberActionPerformed(evt);
            }
        });

        jLabel3.setText("Room Number :");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel4.setText("DASHBOARD");

        Display.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SensorID", "Floor Number", "Room Number", "CO2", "Smoke", "Status Alarm"
            }
        ));
        jScrollPane2.setViewportView(Display);

        message_view_btn.setText("Message View");
        message_view_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                message_view_btnActionPerformed(evt);
            }
        });

        edit_btn.setText("Edit Sensor Allocation ");
        edit_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                edit_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(sensor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(floor_number, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(room_number, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(add_senser_btn))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(message_view_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(edit_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 646, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sensor_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(floor_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(room_number, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(add_senser_btn))
                .addGap(42, 42, 42)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(message_view_btn)
                .addGap(18, 18, 18)
                .addComponent(edit_btn)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    List<SenserAssignModal> senserList = new ArrayList<>();
    private void add_senser_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_senser_btnActionPerformed
        // TODO add your handling code here:
        int i = 0;
        int Al_Status;
        SenserDummy senserDummy = new SenserDummy();
        
        int SensorID = Integer.parseInt(sensor_ID.getText());
        int RoomNumber = Integer.parseInt(room_number.getText());
        int FloorNumber = Integer.parseInt(floor_number.getText());
        int CO2 = senserDummy.co2Level;
        int Smoke = senserDummy.smokeLevel;
        
       
        
                

        senserDummy.setSensorID(SensorID);
        Al_Status = senserDummy.getAlarmStatus();
        SenserAssignModal m = new SenserAssignModal(SensorID, RoomNumber, FloorNumber, CO2, Smoke,Al_Status);
        senserList.add(m);
        DatabaseConnection(m);
        

        i++;
        
       
            for(SenserAssignModal s : senserList){
                System.out.println(s.AlarmStatus);
            }  
        
       
        senserDummy.setVisible(true);
    }//GEN-LAST:event_add_senser_btnActionPerformed

    private void floor_numberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_floor_numberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_floor_numberActionPerformed

    private void message_view_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_message_view_btnActionPerformed
        // TODO add your handling code here:
        
        MessageWindow messageWindow = new MessageWindow();
        messageWindow.setVisible(true);
        
    }//GEN-LAST:event_message_view_btnActionPerformed

    private void edit_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_edit_btnActionPerformed
        // TODO add your handling code here:
        EditWindow editWindow = new EditWindow();
        editWindow.setVisible(true);
    }//GEN-LAST:event_edit_btnActionPerformed

    public void display(){
        int len = getSen().size();
        ArrayList<SenserAssignModal> s = new ArrayList<>();
        s = getSen();
        
        for(SenserAssignModal k: getSen()){
            System.out.println(k.getCO2());
        }
        
      
    }
    public ArrayList<SenserAssignModal> getSen(){
        
        ArrayList<SenserAssignModal> sensorList = new ArrayList<>();
          Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/DBNEW", "root","root1234");
            Statement st = con.createStatement();
            
            
            
            String q = "SELECT * FROM alarm ";
                   
            ResultSet res =st.executeQuery(q);
            
            SenserAssignModal modal;
            
            while(res.next()){
                modal = new SenserAssignModal(res.getInt("SensorID"), res.getInt("Room_Number"), res.getInt("Floor_Number"), res.getInt("CO2"), res.getInt("Smoke"), res.getInt("Alarm_Status"));
                sensorList.add(modal);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(ClientHome.class.getName()).log(Level.SEVERE, null, ex);
        }
        return sensorList;
    }
    
    public void showTable(){
        ArrayList list = getSen();
        DefaultTableModel ms =(DefaultTableModel) Display.getModel();
        ms.setRowCount(0);
        Object row[] = new Object[6];
        String sta ;
        for(SenserAssignModal l : getSen()){
            if(l.getAlarmStatus()==0){
                sta="Deactive";
            }else{
                sta="Active";
            }
            
             row[0]=l.getSensorID();
            row[1]=l.getFloorNumber();
            row[2]=l.getRoomNumber();
            row[3]= l.getCO2();
            row[4]=l.getSmoke();
            row[5] = sta;
            ms.addRow(row);
        }
        
        
        
        
        
        
    }
    
    public void DatabaseConnection(SenserAssignModal m){
        Connection con = null;
        
        try {
            con = DriverManager.getConnection("jdbc:mysql://localhost/DBNEW", "root","root1234");
            Statement st = con.createStatement();
            
            String Insert = "INSERT INTO alarm"+
                    "(SensorID, Room_Number, Floor_Number, CO2, Smoke, Alarm_Status)"+
                    "values('"+m.SensorID+"','"+m.RoomNumber+"','"+m.FloorNumber+"','"+m.CO2+"','"+m.Smoke+"','"+m.AlarmStatus+"')";
            st.execute(Insert);
            System.err.println("Insert Completed");
        } catch (SQLException ex) {
            Logger.getLogger(ClientHome.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        //Connecting With Server Please add the external jar file first
				
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClientHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               
                new ClientHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Display;
    private javax.swing.JButton add_senser_btn;
    private javax.swing.JButton edit_btn;
    private javax.swing.JTextField floor_number;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton message_view_btn;
    private javax.swing.JTextField room_number;
    private javax.swing.JTextField sensor_ID;
    // End of variables declaration//GEN-END:variables
}
